version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: todo_db_mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - todo_mysql_data:/var/lib/mysql

volumes:
  todo_mysql_data: